on:
  push:
    branches:
      - staging
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files NPSOFTWARE.net
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: 160.153.133.159
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          port: 21
          server-dir: /public_html/

      - name: 📂 Sync files pascu.io
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: 92.205.1.205
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          port: 21
          local-dir: ./build/
          server-dir: /public_html/
